version: "3.1"
   
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: j8Rqe.fu

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 4222:4222
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 0Y7jrmp?
  jango:
    image: docker-django-v0.0
    container_name: DjangoMedPlanner
    working_dir: /django
    volumes:
        - ./djangoMedPlanner:/django
    ports:
        - "4223:4223"
    command: python ./djangoMedPlanner/manage.py runserver 4223
  web:
    image: ng:10.0
    container_name: MedPlanner
    working_dir: /angular
    volumes:
        - ./ngMedPlanner:/angular
    ports:
        - "4220:4220"
    command: ng serve --host 0.0.0.0 --port 4220

